---
- name: Configure Could-Init Ubuntu Template
  hosts: all
  remote_user: "{{ PROXMOX.AUTH_USER }}"
  vars:
    node: pvekomputer1
    vmname: ubuntu24.04-cloudimg
    vmid: 999
    imgurl: https://cloud-images.ubuntu.com/noble/20241126/noble-server-cloudimg-amd64.img
    checksum: sha256:4b27ad911f3f33174e31a7c83cbd4d23a3c5f1c3556b09b587287cb3d3435a8a
  tasks:
    - name: Download Ubuntu Cloud Image
      get_url:
        url: "{{ imgurl }}"
        dest: /var/lib/vz/template/iso
        mode: "0600"
        checksum: "{{ checksum }}"
    - name: Install PIP with APT
      apt:
        name: python3-pip
        state: present
    - name: Install Required Python Module
      pip:
        name: proxmoxer
        break_system_packages: true
    - name: Create Base VM
      community.general.proxmox_kvm:
        api_token_id: "{{ PROXMOX.API_TOKEN_ID }}"
        api_token_secret: "{{ PROXMOX.API_TOKEN }}"
        api_user: "{{ PROXMOX.PVE_USER }}"
        api_host: "{{ node }}"
        node: "{{ node }}"
        name: "{{ vmname }}"
        vmid: "{{ vmid }}"
        memory: 2048
        net:
          net0: virtio,bridge=vmbr0
        scsihw: virtio-scsi-pci
        state: present
    - name: Import Cloud Image
      community.general.proxmox_kvm:
        api_token_id: "{{ PROXMOX.API_TOKEN_ID }}"
        api_token_secret: "{{ PROXMOX.API_TOKEN }}"
        api_user: "{{ PROXMOX.PVE_USER }}"
        api_host: "{{ node }}"
        node: "{{ node }}"
        name: "{{ vmname }}"
        vmid: "{{ vmid }}"
        update_unsafe: true
        scsi:
          # should match imgurl filename
          scsi0: local-lvm:0,import-from=/var/lib/vz/template/iso/noble-server-cloudimg-amd64.img
    - name: Configure CD-ROM, Boot Parameter and Serial Console
      community.general.proxmox_kvm:
        api_token_id: "{{ PROXMOX.API_TOKEN_ID }}"
        api_token_secret: "{{ PROXMOX.API_TOKEN }}"
        api_user: "{{ PROXMOX.PVE_USER }}"
        api_host: "{{ node }}"
        node: "{{ node }}"
        name: "{{ vmname }}"
        vmid: "{{ vmid }}"
        update_unsafe: true
        ide:
          ide2: local-lvm:cloudinit
        boot: order=scsi0
        serial:
          serial0: socket
        vga: serial0
    - name: Convert into Template
      community.general.proxmox_kvm:
        api_token_id: "{{ PROXMOX.API_TOKEN_ID }}"
        api_token_secret: "{{ PROXMOX.API_TOKEN }}"
        api_user: "{{ PROXMOX.PVE_USER }}"
        api_host: "{{ node }}"
        node: "{{ node }}"
        name: "{{ vmname }}"
        vmid: "{{ vmid }}"
        state: template
