- name: icn-filkom.ub.ac.id deployment
  hosts: all
  remote_user: "{{ WEB_PROFILE.USER }}"
  vars:
    home: "/home/{{ WEB_PROFILE.USER }}"
    _port:
      app: "{{ WEB_PROFILE.APP_PORT }}"
      host: "{{ WEB_PROFILE.HOST_PORT }}"
    git:
      username: "{{ GITHUB.USERNAME }}"
      pat: "{{ GITHUB.PAT }}"
      owner: "{{ WEB_PROFILE.REPOSITORY.OWNER }}"
      repo: "{{ WEB_PROFILE.REPOSITORY.NAME }}"
      branch: "{{ WEB_PROFILE.REPOSITORY.BRANCH }}"

  tasks:
    - name: Clone remote repository
      ansible.builtin.git:
        repo: "https://{{ git.username }}:{{ git.pat }}@github.com/{{ git.owner }}/{{ git.repo }}.git"
        dest: "{{ home }}/{{ git.repo }}"
        version: "{{ git.branch }}"
        single_branch: true
        depth: 1

    - name: Build Docker Image
      become: true
      community.docker.docker_image:
        name: "{{ git.repo }}:latest"
        source: build
        force_source: true
        build:
          path: "{{ home }}/{{ git.repo }}"
          pull: true
          nocache: false

    - name: Create and run Docker container
      become: true
      community.docker.docker_container:
        name: "{{ git.repo }}"
        image: "{{ git.repo }}:latest"
        ports: ["{{ _port.host }}:{{ _port.app }}"]
        restart_policy: always
