---
- name: Configure target hosts
  hosts: localhost
  vars_files: [config.yaml]

  tasks:
    - name: Add hosts target
      loop: "{{ inventory.hosts }}"
      ansible.builtin.add_host:
        name: "{{ item.ip }}"
        ansible_host: "{{ item.ip }}"
        ansible_user: "{{ item.username }}"
        new_ip: "{{ item.newIP | default(omit) }}"
        groups: target

- hosts: target
  become: true
  gather_facts: false
  vars_files: [config.yaml]

  tasks:
    - name: Gather network facts
      ansible.builtin.setup:
        gather_subset:
          - network

    - name: Remove existing netplan configurations
      ignore_errors: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/netplan/50-cloud-init.yaml"
        - "/etc/netplan/00-installer-config.yaml"
        - "/etc/netplan/01-netcfg.yaml"

    - name: Set static IP configuration
      register: netplan_updated
      ansible.builtin.template:
        src: netplan-config.j2
        dest: "{{ netplanConfigFile }}"
        owner: root
        group: root
        mode: "0644"
      vars:
        target_ip: "{{ new_ip }}"

    - name: Apply netplan configuration
      command: netplan apply
      async: 60
      poll: 0

    # TODO: should verify the new ip actually configured
