---
- name: Configure target hosts
  hosts: localhost
  vars_files: [config.yaml]

  tasks:
    - name: Add hosts dynamically
      loop: "{{ inventory.hosts }}"
      ansible.builtin.add_host:
        name: "{{ item.ip }}"
        ansible_host: "{{ item.ip }}"
        ansible_user: "{{ item.username }}"
        new_ip: "{{ item.newIP | default(omit) }}"
        groups: all

- hosts: all
  become: true
  gather_facts: false
  vars_files: [config.yaml]

  tasks:
    - name: Gather network facts
      ansible.builtin.setup:
        gather_subset:
          - network

    - name: Remove existing netplan configurations
      ignore_errors: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/netplan/50-cloud-init.yaml"
        - "/etc/netplan/00-installer-config.yaml"
        - "/etc/netplan/01-netcfg.yaml"

    - name: Set static IP configuration
      register: netplan_updated
      ansible.builtin.template:
        src: netplan-config.j2
        dest: "{{ netplanConfigFile }}"
        owner: root
        group: root
        mode: "0644"
      vars:
        target_ip: "{{ new_ip }}"

    - name: Apply netplan configuration asynchronously
      ansible.builtin.command: nohup netplan apply &
      async: 10
      poll: 0
      changed_when: true
      when: netplan_updated.changed

    - name: Wait for new IP connection
      when: netplan_updated.changed and new_ip is defined
      block:
        - name: Wait for SSH port to be available on new IP
          ansible.builtin.wait_for:
            host: "{{ new_ip }}"
            port: 22
            delay: 5

        - name: Wait for connection with new IP
          ansible.builtin.wait_for_connection:
            connect_timeout: 20
            sleep: 5
            delay: 5
